### ISSUE TITLE
Hi 

### ISSUE THREAD

**Issue by E-Tan** [amitkurud/mygithubpage#1]
HI just found your issue, how should i contact you? I have been asking around, about how to talk to you (insanity and elektricat but they never responded...), and have missed you. Sorry for the 27 days of waiting!

Kicks in balls.

**Comment by Abyss-Subhacker** [comment]
add me on facebook , search my name

**Comment by amitkurud** [comment]
add me on facebook

**Comment by E-Tan** [comment]
Okay
